### ISSUE TITLE
Missing required header X-App-Id

### ISSUE THREAD

**Issue by wejrox** [r6db/r6api#1]
Hey, I've been using your API in my site and it had suddenly started giving a 400 response with that error above. 
I haven't changed my code, and I've also tried an attempt in postman to make sure I wasn't going crazy!
Curl attempt: `curl "https://r6db.com/api/v2/players?name=JimJoms" -H "X-App-Id: MyRequest"`
This was previously (about a week ago) working but now is not.

**Comment by LaxisB** [comment]
we had to make the api private due to the gdpr.
An email was sent out to all registered apiusers  on the 8th about this, as well as multiple updates in the discord
